spring:
  application:
    name: trendbazaar

  datasource:
    url: jdbc:mysql://localhost:3306/trendbazaar
    username: root
    password: tiger@data

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true

server:
  port: 8082

jwt:
  secret: my_secret_keyjuhkhhljljljljljpiuiuhohlhljoguyfygigkhghk
  expiration:
    time: 86400000   # 1 day in milliseconds
